#!/bin/sh

cd ~/.vim/bundle

git clone https://github.com/tomtom/tcomment_vim.git
git clone https://github.com/kien/ctrlp.vim.git
git clone https://github.com/vim-scripts/a.vim.git
git clone https://github.com/dhruvasagar/vim-table-mode.git
git clone https://github.com/docunext/closetag.vim.git
git clone https://github.com/jlanzarotta/bufexplorer.git
git clone https://github.com/easymotion/vim-easymotion.git
git clone https://github.com/Yggdroot/indentLine.git
git clone https://github.com/jvirtanen/vim-octave.git
git clone https://github.com/chriskempson/base16-vim.git
